<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>ClipShelf</RootNamespace>
    <AssemblyName>ClipShelf</AssemblyName>
    <Version>1.1.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\ClipShelf.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><Resource Include="Assets\AppIcon2.png" /><Content Include="Assets\ClipShelf.ico" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><Content Include="ThirdPartyNotices.txt" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><Content Include="Licenses\*.txt" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><PackageReference Include="System.Drawing.Common" Version="8.0.31" /></ItemGroup>
</Project>
